# Generated by Django 5.1.1 on 2025-09-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='get_data1',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
