# Generated by Django 5.1.1 on 2025-09-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0002_alter_get_data1_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='get_data1',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
