# Generated by Django 5.1.1 on 2025-09-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0003_get_data1_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='get_data5',
            name='achievements',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='get_data1',
            name='objective',
            field=models.CharField(max_length=254),
        ),
    ]
