# Generated by Django 5.1.1 on 2025-09-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0004_get_data5_achievements_alter_get_data1_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='get_data5',
            name='img',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to='media'),
        ),
    ]
