# Generated by Django 5.1.1 on 2025-09-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0006_alter_get_data5_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='get_data5',
            name='img',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='media/'),
        ),
    ]
