# Generated by Django 5.1.1 on 2025-09-20 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0008_alter_get_data5_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='get_data2',
            name='person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='resume_maker.get_data1'),
        ),
        migrations.AddField(
            model_name='get_data3',
            name='person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graduated', to='resume_maker.get_data1'),
        ),
        migrations.AddField(
            model_name='get_data4',
            name='person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='resume_maker.get_data1'),
        ),
        migrations.AddField(
            model_name='get_data5',
            name='person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_info', to='resume_maker.get_data1'),
        ),
        migrations.AddField(
            model_name='get_data6',
            name='person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='undergraduation', to='resume_maker.get_data1'),
        ),
    ]
