# Generated by Django 5.1.1 on 2025-09-26 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0009_get_data2_person_id_get_data3_person_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='get_data2',
            name='person_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='resume_maker.get_data1'),
        ),
        migrations.AlterField(
            model_name='get_data3',
            name='person_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='graduated', to='resume_maker.get_data1'),
        ),
        migrations.AlterField(
            model_name='get_data4',
            name='person_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='resume_maker.get_data1'),
        ),
        migrations.AlterField(
            model_name='get_data5',
            name='person_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='other_info', to='resume_maker.get_data1'),
        ),
        migrations.AlterField(
            model_name='get_data6',
            name='person_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='undergraduation', to='resume_maker.get_data1'),
        ),
    ]
