# Generated by Django 5.1.1 on 2025-10-02 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0014_alter_get_data2_person_id_alter_get_data3_person_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='get_data5',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='get_data2',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='get_data3',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='get_data4',
            name='person_id',
        ),
        migrations.DeleteModel(
            name='get_data6',
        ),
        migrations.DeleteModel(
            name='get_data5',
        ),
        migrations.DeleteModel(
            name='get_data2',
        ),
        migrations.DeleteModel(
            name='get_data3',
        ),
        migrations.DeleteModel(
            name='get_data1',
        ),
        migrations.DeleteModel(
            name='get_data4',
        ),
    ]
