# Generated by Django 5.1.1 on 2025-10-02 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume_maker', '0015_remove_get_data5_person_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='get_data1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('dob', models.DateField(max_length=100)),
                ('objective', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='get_data2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hard_skill', models.CharField(max_length=100)),
                ('soft_skill', models.CharField(max_length=100)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='resume_maker.get_data1')),
            ],
        ),
        migrations.CreateModel(
            name='get_data3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=100)),
                ('inst_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('g_date', models.DateField(max_length=100)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduated', to='resume_maker.get_data1')),
            ],
        ),
        migrations.CreateModel(
            name='get_data4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('comp_name', models.CharField(max_length=100)),
                ('achievement', models.CharField(max_length=100)),
                ('doj', models.DateField(max_length=100)),
                ('dol', models.DateField(max_length=100)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='resume_maker.get_data1')),
            ],
        ),
        migrations.CreateModel(
            name='get_data5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects', models.CharField(max_length=100)),
                ('certificate', models.CharField(max_length=100)),
                ('hobby', models.CharField(max_length=100)),
                ('ability', models.CharField(max_length=100)),
                ('achievements', models.CharField(blank=True, max_length=100, null=True)),
                ('img', models.ImageField(blank=True, max_length=254, null=True, upload_to='uploads/')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_info', to='resume_maker.get_data1')),
            ],
        ),
        migrations.CreateModel(
            name='get_data6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('percent_10', models.CharField(max_length=100)),
                ('percent_12', models.CharField(max_length=100)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='undergraduation', to='resume_maker.get_data1')),
            ],
        ),
    ]
